### ISSUE TITLE
Add words "Xenophobe" and "Xenophobia"

### ISSUE THREAD

**Issue by Showndarya** [Showndarya/Hacktoberfest#140]
Add the words "Xenophobe" and "Xenophobia"

Add the meanings for the verb form of Xenophobe in a file named Xenophobe.json
Add the meanings for the verb form of Xenophobia in a file named Xenophobia.json

Refer Contribution.md for more details on how to contribute.

Comment here if you're are working on this issue to avoid conflicts.
Add reference to this issue i.e Issue #140 in your pull request description.

**Comment by dalanskis** [comment]
I will do this one.
