### ISSUE TITLE
Add words ending with "oss"

### ISSUE THREAD

**Issue by Showndarya** [Showndarya/Hacktoberfest#146]
Add words ending with "oss"

- [x] boss
- [x] loss
- [x] moss
- [x] toss 
- [x] cross
- [x] dross
- [x] floss
- [x] gross
- [x] gloss
- [x] across
- [x] deboss
- [x] kaross
- [x] emboss
- [x] engross
- [x] incross
- [x] bugloss
- [x] motocross
- [x] albatross

Refer [Contribution.md](https://github.com/Showndarya/Hacktoberfest/blob/master/Contribution.md) for more details on how to contribute.

Comment the word/words you're working on  to avoid conflicts.
Add reference to this issue i.e Issue #146 in your pull request description.

**Comment by raghavraman** [comment]
I am working on this
