### ISSUE TITLE
Add word "Recluse"

### ISSUE THREAD

**Issue by Showndarya** [Showndarya/Hacktoberfest#149]
Add the word "Recluse"

Add all the definitions for the adjective form of Recluse in a file named ```Recluse_adjective.json```
Add all the definitions for the noun form of Recluse in a file named ```Recluse_noun.json```

Refer Contribution.md for more details on how to contribute.

Comment here if you're are working on this issue to avoid conflicts.
Add reference to this issue i.e Issue #149 in your pull request description.

**Comment by nihitb06** [comment]
I'll work on it
