### ISSUE TITLE
Add word "Quintessential

### ISSUE THREAD

**Issue by Showndarya** [Showndarya/Hacktoberfest#200]
Add the word "Quintessential"

Add all the definitions of ```Quintessential``` in a file named ```Quintessential.json```

Refer Contribution.md for more details on how to contribute.

Comment here if you're are working on this issue to avoid conflicts.
Add reference to this issue i.e Issue #200 in your pull request description.

**Comment by bagshik** [comment]
This one's for me, love the sound of this word :smile:
