### ISSUE TITLE
Add words "Appal" and "Appalling"

### ISSUE THREAD

**Issue by Showndarya** [Showndarya/Hacktoberfest#201]
Add the words "Appal" and "Appalling"

Add all the definitions of ```Appal``` in a file named ```Appal.json```
Add all the definitions of ```Appalling``` in a file named ```Appalling.json```

Refer Contribution.md for more details on how to contribute.

Comment here if you're are working on this issue to avoid conflicts.
Add reference to this issue i.e Issue #201 in your pull request description.

**Comment by FLeXyo** [comment]
i'll do it

**Comment by SheW0lf** [comment]
I would like to work on this! 😄
