### ISSUE TITLE
Add words ending with "ate"

### ISSUE THREAD

**Issue by Showndarya** [Showndarya/Hacktoberfest#221]
Add words ending with "ate"

- [x] Abbreviate
- [x] Accurate
- [x] Affectionate
- [x] Approximate
- [x] Appropriate
- [x] Certificate
- [x] Climate
- [x] Considerate
- [x] Desperate
- [x] Deliberate
- [x] Duplicate
- [x] Estimate
- [x] Fortunate
- [x] Felicitate
- [x] Graduate
- [x] Immediate
- [x] Moderate
- [x] Passionate
- [x] Private
- [x] Separate
- [x] Ultimate
- [X] Obfuscate
- [X] Obliterate
- [X] Emancipate
- [X] Exaggerate
- [X] Consolidate
- [X] Accumulate
- [X] Appreciate
- [X] Disproportionate
- [X] Compensate
- [X] Superstimulate
- [X] Depreciate 

Refer [Contribution.md](https://github.com/Showndarya/Hacktoberfest/blob/master/Contribution.md) for more details on how to contribute.

Comment the word/words you're working on  to avoid conflicts.
Add reference to this issue i.e Issue #221 in your pull request description.

**Comment by MichaelNZ404** [comment]
I'll do:
  Abbreviate
  Accurate
  Affectionate
  Approximate
  Appropriate

**Comment by 20matan** [comment]
I'll do:

Certificate
  Climate
  Considerate
  Desperate
  Deliberate

**Comment by akashraj98** [comment]
I'll do:
Disproportionate
Appreciate
Accumulate

**Comment by PHOcean01** [comment]
I'll do:
Fortunate
Duplicate

**Comment by goelrohan6** [comment]
adding superstimulate

**Comment by goelrohan6** [comment]
@Showndarya added Superstimulate #327
