### ISSUE TITLE
Add words "Complacent" and "Complaisant" 

### ISSUE THREAD

**Issue by Showndarya** [Showndarya/Hacktoberfest#226]
Add words ```Complacent``` and ```Complaisant```

Add all the definitions of ```Complacent``` in a file named ```Complacent.json```
Add all the definitions of ```Complaisant``` in a file named ```Complaisant.json```

Refer Contribution.md for more details on how to contribute.

Comment here if you're are working on this issue to avoid conflicts.
Add reference to this issue i.e Issue # in your pull request description.

**Comment by MichaelNZ404** [comment]
I'll take this issue.
