### ISSUE TITLE
Add words "Optimist", "Pessimist" and "Pessimistic"

### ISSUE THREAD

**Issue by Showndarya** [Showndarya/Hacktoberfest#235]
Add words ```Optimist```, ```Pessimist``` and ```Pessimistic```

Add all the definitions of ```Optimist``` in a file named ```Optimist.json```
Add all the definitions of ```Pessimist``` in a file named ```Pessimist.json```
Add all the definitions of ```Pessimistic``` in a file named ```Pessimistic.json```

Refer Contribution.md for more details on how to contribute.

Comment here if you're are working on this issue to avoid conflicts.
Add reference to this issue i.e Issue #235 in your pull request description.

**Comment by dionisioC** [comment]
Let me check this

**Comment by RootPixl** [comment]
Check my PR @Showndarya
