### ISSUE TITLE
Add words "Amicable" and "Rancorous"

### ISSUE THREAD

**Issue by Showndarya** [Showndarya/Hacktoberfest#243]
Add words ```Amicable``` and ```Rancorous```

Add all the definitions of ```Amicable``` in a file named ```Amicable.json```
Add all the definitions of ```Rancorous``` in a file named ```Rancorous.json```

Refer Contribution.md for more details on how to contribute.

Comment here if you're are working on this issue to avoid conflicts.
Add reference to this issue i.e Issue #243 in your pull request description.

**Comment by cnuis2cool** [comment]
I will do it

**Comment by Showndarya** [comment]
Hey @cnuis2cool 

Please add ```Rancorous``` only. Amicable has been added already.

Thanks for contributing!
