### ISSUE TITLE
Add words "Equilibrium" and "Equipoise"

### ISSUE THREAD

**Issue by Showndarya** [Showndarya/Hacktoberfest#244]
Add words ```Equilibrium``` and ```Equipoise```

Add all the definitions of ```Equilibrium``` in a file named ```Equilibrium.json```
Add all the definitions of ```Equipoise``` as a noun in a file named ```Equipoise_noun.json```
Add all the definitions of ```Equipoise``` as a verb in a file named ```Equipoise_verb.json```

Refer Contribution.md for more details on how to contribute.

Comment here if you're are working on this issue to avoid conflicts.
Add reference to this issue i.e Issue #244 in your pull request description.

**Comment by OutrageousStop** [comment]
I will do it.
