### ISSUE TITLE
Add words "Aroma", "Petrichor" and "Tang"

### ISSUE THREAD

**Issue by Showndarya** [Showndarya/Hacktoberfest#252]
Add words ```Aroma```, ```Petrichor``` and ```Tang```

Add all the definitions of ```Aroma``` in a file named ```Aroma.json```
Add all the definitions of ```Petrichor``` in a file named ```Petrichor.json```
Add all the definitions of ```Tang``` in a file named ```Tang.json```

Refer Contribution.md for more details on how to contribute.

Comment here if you're are working on this issue to avoid conflicts.
Add reference to this issue i.e Issue #252 in your pull request description.

**Comment by whitemalt** [comment]
I working on it

**Comment by whitemalt** [comment]
done, Petrichor is exist. so I will do nothing
