### ISSUE TITLE
Add words "Protagonist" and "Antagonist"

### ISSUE THREAD

**Issue by Showndarya** [Showndarya/Hacktoberfest#264]
Add words ```Protagonist``` and ```Antagonist```

Add all the definitions of ```Protagonist``` in a file named ```Protagonist.json```
Add all the definitions of ```Antagonist``` in a file named ```Antagonist.json```

Refer Contribution.md for more details on how to contribute.

Comment here if you're are working on this issue to avoid conflicts.
Add reference to this issue i.e Issue #264 in your pull request description.

**Comment by abhy-kumar** [comment]
Done!
