### ISSUE TITLE
Add words "Profound" and "Superficial"

### ISSUE THREAD

**Issue by Showndarya** [Showndarya/Hacktoberfest#266]
Add words ```Profound``` and ```Superficial```

Add all the definitions of ```Profound``` as an adjective in a file named ```Profound_adjective.json```
Add all the definitions of ```Profound``` as an noun in a file named ```Profound_noun.json```
Add all the definitions of ```Superficial``` in a file named ```Superficial.json```

Refer Contribution.md for more details on how to contribute.

Comment here if you're are working on this issue to avoid conflicts.
Add reference to this issue i.e Issue #266 in your pull request description.

**Comment by Harrison1** [comment]
yeah, i'll do it
