### ISSUE TITLE
Add word "Mountain"

### ISSUE THREAD

**Issue by mdb1** [Showndarya/Hacktoberfest#2681]
Add all the definitions of `Mountain` in a file named `Mountain.json` in folder `M`

Refer [CONTRIBUTING.md](https://github.com/Showndarya/Hacktoberfest/blob/master/CONTRIBUTING.md) for more details on how to contribute.

Comment the words you'll be adding if you're are working on this issue to avoid conflicts.
Add reference to this issue i.e Issue # in your pull request description.

**Comment by nehal6657** [comment]
can it be assigned to me

**Comment by iamkumar-gaurav** [comment]
may i have your permission for this task sir..
