### ISSUE TITLE
Add words "Scepticism" and "Conviction"

### ISSUE THREAD

**Issue by Showndarya** [Showndarya/Hacktoberfest#297]
Add words ```Scepticism``` and ```Conviction```

Add all the definitions of ```Scepticism``` in a file named ```Scepticism.json```
Add all the definitions of ```Conviction``` in a file named ```Conviction.json```

Refer Contribution.md for more details on how to contribute.

Comment here if you're are working on this issue to avoid conflicts.
Add reference to this issue i.e Issue #297 in your pull request description.

**Comment by Bharat23** [comment]
I can pick it up

**Comment by Bharat23** [comment]
Done!! #301
