### ISSUE TITLE
Add words "Credulity" and "Cynicism"

### ISSUE THREAD

**Issue by Showndarya** [Showndarya/Hacktoberfest#298]
Add words ```Credulity``` and ```Cynicism```

Add all the definitions of ```Credulity``` in a file named ```Credulity.json```
Add all the definitions of ```Cynicism``` in a file named ```Cynicism.json```

Refer Contribution.md for more details on how to contribute.

Comment here if you're are working on this issue to avoid conflicts.
Add reference to this issue i.e Issue #298 in your pull request description.

**Comment by iamgrawal** [comment]
Heya, I would like to work on this issue.
