### ISSUE TITLE
Add words "Quiver", "Quaver" and "Quake"

### ISSUE THREAD

**Issue by Showndarya** [Showndarya/Hacktoberfest#303]
Add words ```Quiver```, ```Quaver``` and ```Quake```

Add all the definitions of ```Quiver``` in a file named ```Quiver.json```
Add all the definitions of ```Quaver``` in a file named ```Quaver.json```
Add all the definitions of ```Quake``` in a file named ```Quake.json```

Refer Contribution.md for more details on how to contribute.

Comment here if you're are working on this issue to avoid conflicts.
Add reference to this issue i.e Issue #303 in your pull request description.

**Comment by dionisioC** [comment]
Working on this
