### ISSUE TITLE
Add words "Vitality", "Vivacity" and "Vigour"

### ISSUE THREAD

**Issue by Showndarya** [Showndarya/Hacktoberfest#306]
Add words ```Vitality```, ```Vivacity``` and ```Vigour```

Add all the definitions of ```Vitality``` in a file named ```Vitality.json```
Add all the definitions of ```Vivacity``` in a file named ```Vivacity.json```
Add all the definitions of ```Vigour``` in a file named ```Vigour.json```

Refer Contribution.md for more details on how to contribute.

Comment here if you're are working on this issue to avoid conflicts.
Add reference to this issue i.e Issue # in your pull request description.

**Comment by dionisioC** [comment]
Working on this
