### ISSUE TITLE
Add words "Benediction", "Benefactor" and "Beneficiary"

### ISSUE THREAD

**Issue by Showndarya** [Showndarya/Hacktoberfest#325]
Add words ```Benediction```, ```Benefactor``` and ```Beneficiary```

Add all the definitions of ```Benediction``` in a file named ```Benediction.json```
Add all the definitions of ```Benefactor``` in a file named ```Benefactor.json```
Add all the definitions of ```Beneficiary``` in a file named ```Beneficiary.json```

Refer Contribution.md for more details on how to contribute.

Comment here if you're are working on this issue to avoid conflicts.
Add reference to this issue i.e Issue #325 in your pull request description.

**Comment by anmol8399** [comment]
I would like to work on this. Can I take this issue?

**Comment by Showndarya** [comment]
Surely.
