### ISSUE TITLE
Add word "Zonoid"

### ISSUE THREAD

**Issue by falcon883** [Showndarya/Hacktoberfest#3327]
Add all the definitions of `Zonoid` in a file named `Zonoid.json` in folder `Z`

Refer [CONTRIBUTING.md](https://github.com/Showndarya/Hacktoberfest/blob/master/CONTRIBUTING.md) for more details on how to contribute.

Comment the words you'll be adding if you're are working on this issue to avoid conflicts.
Add reference to this issue i.e Issue # in your pull request description.

**Comment by kcamacho1** [comment]
> Add all the definitions of `Zonoid` in a file named `Zonoid.json` in folder `Z`
> 
> Refer [CONTRIBUTING.md](https://github.com/Showndarya/Hacktoberfest/blob/master/CONTRIBUTING.md) for more details on how to contribute.
> 
> Comment the words you'll be adding if you're are working on this issue to avoid conflicts. Add reference to this issue i.e Issue # in your pull request description.

Hello I would like to contribute to this please
