### ISSUE TITLE
Add Word "Armscye"

### ISSUE THREAD

**Issue by teofanis** [Showndarya/Hacktoberfest#3421]
Add all the definitions of `Armscye` in a file named `Armscye.json` in folder `A`

Refer [CONTRIBUTING.md](https://github.com/Showndarya/Hacktoberfest/blob/master/CONTRIBUTING.md) for more details on how to contribute.

Comment the words you'll be adding if you're are working on this issue to avoid conflicts.
Add reference to this issue i.e Issue # in your pull request description.

**Comment by cscipher** [comment]
I'm working on this!

**Comment by teofanis** [comment]
I had already added it
