### ISSUE TITLE
Add words "Yore", "Immemorial","Epoch" and "Ancient"

### ISSUE THREAD

**Issue by Showndarya** [Showndarya/Hacktoberfest#357]
Add words ```Yore```, ```Immemorial```, ```Epoch``` and ```Ancient```

Add all the definitions of ```Yore``` in a file named ```Yore.json``` in folder ```Y```
Add all the definitions of ```Immemorial``` in a file named ```Immemorial.json``` in folder ```I```
Add all the definitions of ```Ancient``` in a file named ```Ancient.json``` in folder ```A```
Add all the definitions of ```Epoch``` in a file named ```Epoch.json``` in folder ```E```

Refer Contribution.md for more details on how to contribute.

Comment here if you're are working on this issue to avoid conflicts.
Add reference to this issue i.e Issue #357 in your pull request description.

**Comment by diegowifi** [comment]
Working on it 😄

**Comment by diegowifi** [comment]
Done, already did a PR 👍

**Comment by Showndarya** [comment]
```Yore``` is still left to be included.
