### ISSUE TITLE
Add words "Anxiety", "Consternation","Disquietude" and "Perturbation"

### ISSUE THREAD

**Issue by Showndarya** [Showndarya/Hacktoberfest#363]
Add words ```Anxiety```, ```Consternation```, ```Disquietude``` and ```Perturbation```

Add all the definitions of ```Anxiety``` in a file named ```Anxiety.json``` in folder ```A```
Add all the definitions of ```Consternation``` in a file named ```Consternation.json``` in folder ```C```
Add all the definitions of ```Disquietude``` in a file named ```Disquietude.json``` in folder ```D```
Add all the definitions of ```Perturbation``` in a file named ```Perturbation.json``` in folder ```P```

Refer Contribution.md for more details on how to contribute.

Comment here if you're are working on this issue to avoid conflicts.
Add reference to this issue i.e Issue #363 in your pull request description.

**Comment by ianmah** [comment]
Working on it!
