### ISSUE TITLE
Add word "Work" and words related to "Work"

### ISSUE THREAD

**Issue by Showndarya** [Showndarya/Hacktoberfest#364]
Add word "Work" and words related to "Work"

- [x] Work
- [x] Labour
- [x] Toil
- [x] Exertion
- [x] Effort
- [x] Drudgery
- [x] Slog
- [x] Industry
- [x] Service
- [x] Spadework
- [x] Profession
- [x] Career
- [x] Vocation 
- [x] Employ
- [x] Trade
- [x] Drive
- [x] Excursion
- [x] Commute
- [x] Fly
- [x] Post
- [x] Position

Refer [Contribution.md](https://github.com/Showndarya/Hacktoberfest/blob/master/Contribution.md) for more details on how to contribute.

Comment the word/words you're working on to avoid conflicts.
Add reference to this issue i.e Issue #364 in your pull request description.

**Comment by skprabhanjan** [comment]
@Showndarya  , Adding the words **Work,Labour,Industry,Profession,Career, Employ, Commute**

**Comment by harshitagupta30** [comment]
@Showndarya I'll work on the rest of the words in the list
