### ISSUE TITLE
Add words "Offend", "Outburst" and "Objectionable"

### ISSUE THREAD

**Issue by Showndarya** [Showndarya/Hacktoberfest#399]
Add words ```Offend```, ```Outburst``` and ```Objectionable```

Add all the definitions of ```Offend``` in a file named ```Offend.json``` in folder ```O```
Add all the definitions of ```Outburst``` in a file named ```Outburst.json``` in folder ```O```
Add all the definitions of ```Objectionable``` in a file named ```Objectionable.json``` in folder ```O```

Refer Contribution.md for more details on how to contribute.

Comment here if you're are working on this issue to avoid conflicts.
Add reference to this issue i.e Issue #399 in your pull request description.

**Comment by NarcissNarc** [comment]
@Showndarya Made the requested changes, please review the PR
