### ISSUE TITLE
Add words "Ravishing", "Entrance" and "Beguile"

### ISSUE THREAD

**Issue by Showndarya** [Showndarya/Hacktoberfest#400]
Add words ```Ravishing```, ```Entrance``` and ```Beguile```

Add all the definitions of ```Ravishing``` in a file named ```Ravishing.json``` in folder ```R```
Add all the definitions of ```Entrance``` in a file named ```Entrance.json``` in folder ```E```
Add all the definitions of ```Beguile``` in a file named ```Beguile.json``` in folder ```B```

Refer Contribution.md for more details on how to contribute.

Comment here if you're are working on this issue to avoid conflicts.
Add reference to this issue i.e Issue #400 in your pull request description.

**Comment by dnivra26** [comment]
working
