### ISSUE TITLE
Add words "Enchant", "Enrapture" and "Mesmerize"

### ISSUE THREAD

**Issue by Showndarya** [Showndarya/Hacktoberfest#401]
Add words ```Enchant```, ```Enrapture``` and ```Mesmerize```

Add all the definitions of ```Enchant``` in a file named ```Enchant.json``` in folder ```E```
Add all the definitions of ```Enrapture``` in a file named ```Enrapture.json``` in folder ```E```
Add all the definitions of ```Mesmerize``` in a file named ```Mesmerize.json``` in folder ```M```

Refer Contribution.md for more details on how to contribute.

Comment here if you're are working on this issue to avoid conflicts.
Add reference to this issue i.e Issue #401 in your pull request description.

**Comment by sal2701** [comment]
Hey, I would like to do this!

**Comment by Showndarya** [comment]
@sal2701  Sure

**Comment by sal2701** [comment]
Done
