### ISSUE TITLE
Add word "Welter"

### ISSUE THREAD

**Issue by Showndarya** [Showndarya/Hacktoberfest#41]
Create a folder for "W" and add the word "Welter"

Add the meanings for the verb form of Welter in a file named ```Welter_verb.json```
Add the meaning for the noun form of Refractory in a file named ```Welter_noun.json```

Refer Contribution.md for more details on how to contribute.

Comment here if your are working on this issue to avoid conflicts.
Add reference to this issue i.e Issue #41 in your pull request description.

**Comment by mbabatunde** [comment]
@Showndarya I'm taking this one
