### ISSUE TITLE
Add word "Carnival" and words related to "Carnival"

### ISSUE THREAD

**Issue by Showndarya** [Showndarya/Hacktoberfest#417]
Add word "Carnival" and words related to "Carnival"

- [x] Carnival
- [x] Fete
- [x] Fair
- [x] Fiesta
- [x] Gala
- [x] Jamboree
- [x] Celebrate
- [x] Pageant
- [x] Funfair
- [x] Cavalcade
- [x] Extravaganza
- [x] Eisteddfod
- [x] Ritual

Refer [Contribution.md](https://github.com/Showndarya/Hacktoberfest/blob/master/Contribution.md) for more details on how to contribute.

Comment the word/words you're working on to avoid conflicts.
Add reference to this issue i.e Issue #417 in your pull request description.

**Comment by phanindra789** [comment]
Working on ritual, gala, and funfair.

**Comment by bilalvur** [comment]
Working on fete, fiesta, jamboree, cavalcade, extravaganza and eisteddfod.
