### ISSUE TITLE
PR #427 introduced invalid json

### ISSUE THREAD

**Issue by jukefr** [Showndarya/Hacktoberfest#433]
You can see here that the JSON parsing failed https://travis-ci.org/Showndarya/Hacktoberfest/builds/438744297

The reason is that you cannot have a trailing comma in JSON, only Javascript objects.

Also there should be a warning about the lowercase filename but that's another issue

**Comment by Showndarya** [comment]
@jukefr I corrected that. It is a success now. Thanks a lot for the help.
