### ISSUE TITLE
Travis test ignore first letter of filename for some reason

### ISSUE THREAD

**Issue by jukefr** [Showndarya/Hacktoberfest#434]
I'll try and figure out why, thought about simply renaming every file in the travis script but that requires alot of work and overhead for little gain, it is certainly doable, you have to configure the git on the travis instance and make a new commit etc.
Might as well have a cron job or something to it recursively and periodically over the entirety of the repo and make a single commit...

**Comment by jukefr** [comment]
Oh yeah easy catch I'm checking if the first letter is a capital in `A/Axxxxx` instead of the actual filename.

**Comment by Showndarya** [comment]
Yaaaa. Was working on it. Thanks!
