### ISSUE TITLE
Add words starting with letter "U"

### ISSUE THREAD

**Issue by Showndarya** [Showndarya/Hacktoberfest#452]
Add words starting with letter "U"

- [x] Ultimatum
- [x] Umbrage
- [x] Uncouth
- [x] Uncanny
- [x] Unassailable
- [x] Unctuous
- [x] Undulating
- [x] Unequivocal
- [x] Unerringly
- [x] Unfeigned

Refer [Contribution.md](https://github.com/Showndarya/Hacktoberfest/blob/master/Contribution.md) for more details on how to contribute.

Comment the word/words you're working on to avoid conflicts.
Add reference to this issue i.e Issue #452 in your pull request description.

**Comment by Deumus74** [comment]
Uncouth, Uncanny

**Comment by Deumus74** [comment]
Uncouth, Uncanny #455

**Comment by Deumus74** [comment]
Uncouth, Uncanny #456

**Comment by MrWako** [comment]
working on Unassailable, Undulating!

**Comment by pvivera** [comment]
working on Unequivoval
