### ISSUE TITLE
"help-wanted" add .gitignore

### ISSUE THREAD

**Issue by jukefr** [Showndarya/Hacktoberfest#492]
a `.DS_Store` (macos system file) got in the repo
somebody could add a gitignore and clean up any uneeded files

**Comment by msyrgiy** [comment]
I can do it. Which files are uneeded except .DB_Store?

**Comment by msyrgiy** [comment]
I have some troubles with pushing. It seems my permission denied.

**Comment by jukefr** [comment]
you need to fork and make a pull request

**Comment by msyrgiy** [comment]
Yes, I did a separate branch with my changes

**Comment by msyrgiy** [comment]
Got the problem. I'm in progress

**Comment by Showndarya** [comment]
@jukefr @msyrgiy Thanks a lot for this
