### ISSUE TITLE
Add word "Famous" and words related to "Famous"

### ISSUE THREAD

**Issue by Showndarya** [Showndarya/Hacktoberfest#543]
Add word "Famous" and words related to "Famous"

- [x] Famous
- [x] Impeccable
- [x] Illustrious
- [x] Venerable
- [x] Eminent
- [x] Preeminent
- [x] Prominent
- [x] Paramount
- [x] Prestigious
- [x] Notable
- [x] Noteworthy
- [x] Acclaimed
- [x] Distinguished
- [x] Exalted
- [x] August
- [x] Aristocratic
- [x] Regal
- [x] Royal
- [x] Imperial
- [x] Majestic
- [x] Dignified
- [x] Solemn
- [x] Exemplary
- [x] Honourable

Refer [Contribution.md](https://github.com/Showndarya/Hacktoberfest/blob/master/Contribution.md) for more details on how to contribute.

Comment the word/words you're working on to avoid conflicts.
Add reference to this issue i.e Issue #543 in your pull request description.

**Comment by RafaelDavisH** [comment]
working on Famous, Impeccable, Illustrious, and Venerable.

**Comment by RafaelDavisH** [comment]
Working on Eminent, Preeminent, Prominent and Paramount.

**Comment by gnsharma** [comment]
Working on Prestigious, Notable, Noteworthy, and Acclaimed.

**Comment by RafaelDavisH** [comment]
Working on Distinguished,  Exalted, August, and Aristocratic.

**Comment by RafaelDavisH** [comment]
Working on Regal, Royal, Imperial,  and Majestic.

**Comment by RafaelDavisH** [comment]
Working on Dignified, Solemn, Exemplary, and Honourable.

**Comment by harshitagupta30** [comment]
Working on Prestigious, Notable, Noteworthy, Acclaimed
