### ISSUE TITLE
Add a rest api

### ISSUE THREAD

**Issue by jukefr** [Showndarya/Hacktoberfest#610]
We have all this data we might as well start making it available :)

I propose we add a very simply API to access these JSON files.

Here is a basic spec idea :
Starting with our main route `/`

`/` -> listing of LETTERS (or anything really)
`/LETTER/` -> listing of WORDS that start with LETTER
`/LETTER/WORD` -> actual word definition

**maybe add a fuzzy search also**

It might be worth to take a look at `lowdb` and especially `json-server` that can offer an API in seconds with a json file. I am unsure if it works with multiple files out of the box.

The main idea would be to keep the data as is (so no unique id added in the files or something like that) to make contributing stay as easy as possible.

As for deployment I strongly recommend https://zeit.co/now as it is free, integrated with github and perfect for continuous release (and easy)

edit: 1GB bandwidth might be low

**Comment by jukefr** [comment]
next step would be a front-end eventually once this is in place

**Comment by jukefr** [comment]
if we do it on js we could also apply for a https://js.org site

**Comment by krishnaprasanthg** [comment]
indeed @jukefr the js.org perfectly makes sense.

**Comment by Showndarya** [comment]
@jukefr @krishnaprasanthg I was planning to make a Google extension out of this or something of that sort. API is the next step, eventually.

I don't know if Google extension is the best of ideas. Suggest if there's anything better

**Comment by krishnaprasanthg** [comment]
Well Google extension is good to make good use of the data. Maybe like a hover tooltip that does a search in the data for information (thesaurus).

What I feel would be good is to implement #612 first. That will push the first timers to pour in more data (as this will come to slowdown after Hacktoberfest). Gaming factor is always good. Maybe week's top 5 contributes/day top5 .

Once everything is ended then we can implement as a Google extension...

Anyway that's my 2 cents.

**Comment by jukefr** [comment]
created pr #802 relating to this but I welcome some more work on it as it is very rough
