### ISSUE TITLE
Add words starting with "Wh"

### ISSUE THREAD

**Issue by Showndarya** [Showndarya/Hacktoberfest#695]
Add words starting with ```Wh```

- [x] Whiff 
- [ ] Whim
- [x] Whine 
- [ ] Whinny
- [ ] Whit
- [ ] Whittle
- [ ] Wholesome
- [ ] Whorl
- [ ] Whir
- [ ] Whit
- [ ] Whiz
- [ ] Whamo
- [ ] Whelm
- [ ] Whelp
- [ ] Wheedling
- [x] Wheel
- [x] Wheelie
- [ ] Wheelbarrow
- [ ] Wheeping
- [x] Wheeple
- [x] Whereabout
- [x] Wherry
- [ ] Whetstone
- [ ] Whiffle
- [ ] Whilst
- [ ] Whine
- [ ] Whip
- [ ] Whirl
- [X] Whoop

Refer [CONTRIBUTING.md](https://github.com/Showndarya/Hacktoberfest/blob/master/CONTRIBUTING.md)  for more details on how to contribute.

Comment the words you'll be adding if you're are working on this issue to avoid conflicts.
Add reference to this issue i.e Issue #695 in your pull request description.

**Comment by syyam** [comment]
taken

**Comment by ejr004** [comment]
- Wheeple
- Whereabout
- Wherry

**Comment by davidmorosini** [comment]
Adding

- Wheel
- Wheelie

**Comment by kx-chen** [comment]
Adding 
* Whiff
* Whine
