### ISSUE TITLE
The link is broken

### ISSUE THREAD

**Issue by naoppy** [Showndarya/Hacktoberfest#767]
In https://github.com/Showndarya/Hacktoberfest/blob/master/README.md, link "Refer the template provided below to add your word" is broken.
The link name is "Contribution.md", but the real name is "CONTRIBUTING.md".

**Comment by Showndarya** [comment]
@naoppy 

Fixing it. Thanks for pointing it out!

**Comment by Showndarya** [comment]
@naoppy 

Thank you for the PR.
