### ISSUE TITLE
Add words ending with 

### ISSUE THREAD

**Issue by Showndarya** [Showndarya/Hacktoberfest#807]
Add word "[Word]" and words related to "[Word]"

- [ ] Word1
- [ ] Word1
- [ ] Word1
- [ ] Word1

Refer [CONTRIBUTING.md](https://github.com/Showndarya/Hacktoberfest/blob/master/CONTRIBUTING.md)  for more details on how to contribute.

Comment the words you'll be adding if you're are working on this issue to avoid conflicts.
Add reference to this issue i.e Issue # in your pull request description.

**Comment by Reisande** [comment]
I can work on this.

**Comment by senatormailman** [comment]
Oh this is neat! I'm not sure if I am going about this the right way, but I would like to contribute the following words:

Authenticate
Automate
Assimilate
Associate

I only am listing 4 because I want to let others take a shot as well. I will fork this repo!

**Comment by ernestst** [comment]
Mate, late, hate, calibrate

**Comment by abidishajia** [comment]
Added aggravate and aggregate.

**Comment by weberjacob** [comment]
Added Karate and Imitate.

**Comment by senatormailman** [comment]
Words Added, sorry for the holdup!

**Comment by rosaxny** [comment]
-  Suppurate
- Superannuate
- Triumvirate

**Comment by seanmaxwell** [comment]
I will add Violate

**Comment by Tillvf** [comment]
Liquidate
Mutilate

**Comment by verascity** [comment]
I'll grab:
Officiate
Obligate
Pomegranate
Proportionate

:)

**Comment by nawwx3** [comment]
Truncate

**Comment by rosaxny** [comment]
- Fascinate
- Gesticulate
- Hallucinate

**Comment by dbugshe2** [comment]
I'll be adding

- Conglomerate
- Commensurate
-  Cogitate
-  Commentate
-  Degenerate
-  Extrapolate
-  Equate
-  Equivocate
-  Fabricate

**Comment by sdsalas10** [comment]
I'll add:

- Appreciate
- Baccalaureate
- Retaliate

**Comment by sdsalas10** [comment]
> I'll add:
> 
> * Appreciate
> * Baccalaureate
> * Retaliate

*The word Appreciate was already in the code.

**Comment by Nbsande** [comment]
I'll take 
Multiarticulate

**Comment by vodkanoya** [comment]
I'll be adding the following:

- Desecrate
- Deflate
- Satiate
- Undulate
- Understate

**Comment by bhushan-borole** [comment]
I will add:

- Delate
- Carate

**Comment by karlmarx** [comment]
I'll add dispensate.

**Comment by Madelene** [comment]
I will add:

- Lyrate
- Ultrafiltrate
- Proconsulate
