### ISSUE TITLE
Add words starting with "Di"

### ISSUE THREAD

**Issue by Showndarya** [Showndarya/Hacktoberfest#884]
Add words starting with ```Di```

- [ ] Diatribe
- [ ] Dilettante
- [ ] Diminutive
- [ ] Discern
- [x] Disdain
- [ ] Disgruntled
- [ ] Disheveled
- [x] Dismantle
- [ ] Disparage
- [ ] Disparate
- [ ] Dispersed
- [ ] Disseminate
- [ ] Dissent
- [ ] Distraught
- [ ] Diversity
- [ ] Divulge
- [ ] Dismantle

Refer [CONTRIBUTING.md](https://github.com/Showndarya/Hacktoberfest/blob/master/CONTRIBUTING.md)  for more details on how to contribute.

Comment the words you'll be adding if you're are working on this issue to avoid conflicts.
Add reference to this issue i.e Issue #884 in your pull request description.

**Comment by Simply007** [comment]
I am about to grab Diversity @Showndarya OK?

**Comment by ixjosemi** [comment]
Im going to add "Dialer", "Dinosaur", "Dip", "Distance", "Disease", "Diode"

**Comment by pasanjaya** [comment]
I am going to add Disdain..

**Comment by Krazyman** [comment]
I am going to add Digit.

**Comment by EmiIiaClarke** [comment]
I am to add dilate

**Comment by gowtham5699** [comment]
I am going to add Dismantle @Showndarya .

**Comment by jcasteele** [comment]
Going to add "diligent."

**Comment by Akhil789** [comment]
I am going to add Disparage

**Comment by gowtham5699** [comment]
Added Diatribe.

**Comment by gowtham5699** [comment]
Adding Disgruntled.

**Comment by gowtham5699** [comment]
Adding Dilettante.

**Comment by matejgera** [comment]
Going to add "Disheveled" and "Dispersed"

**Comment by goore3** [comment]
Going to add Discern

**Comment by kurokochin** [comment]
I'll add Diagram

**Comment by akshaychopra96** [comment]
I will add Distraught, is it alright?

**Comment by charBap** [comment]
Going to Add Disseminate

**Comment by rra94** [comment]
I can take dissent and divulge.

**Comment by thanhcng** [comment]
I'll add "diminutive", is it ok?
