### ISSUE TITLE
Fix all file names to the correct structure

### ISSUE THREAD

**Issue by mreguly** [Showndarya/Hacktoberfest#970]
I am about to fix all file names in folders to this structure [(your-word)_(parts-of-speech)].json. 

My script will merge new and existing file into one file with correct file name.

**Comment by prnvdixit** [comment]
Since the relevant PR seems to fail on Travis and there are a lot of conflicts (eg. Abandon (with part of speech verb), as well as Abandon_verb both, are present etc.), it can be done carefully one at a time. Started this off with a new PR :smile:
